name: Cypres with Cucumber end-to-end tests
on: [push]
permissions:
  contents: write
jobs:
  cypress-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci    
      - name: Install Dependencies
        run: npm install cypress --save-dev 
      - name: Cypress run
        run: npm run test:allure
      - name: Copy History
        if: always()
        run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history || true
      - name: Generate report
        run: npm run generate
      - name: Upload Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: allure-results
          path: ./allure-results
      - uses: actions/upload-artifact@v2
        if: always()
        with: 
          name: allure-report
          path: ./allure-report
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./allure-report
          target-folder: docs


    
